FROM node:16.15.0

ADD . ./

ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
ENV NEW_RELIC_LOG=stdout

ENV NEW_RELIC_APP_NAME=sltv
ENV NEW_RELIC_LICENSE_KEY=b0070abf1af437d97fc440b51c0119dbFFFFNRAL



RUN node -r newrelic index.js
